# Generated by Django 3.2.9 on 2021-12-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер'),
        ),
    ]
