# Generated by Django 3.2.9 on 2021-12-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20211207_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='json_path',
            field=models.TextField(blank=True, verbose_name='Путь к Json'),
        ),
    ]
