# Generated by Django 3.2.9 on 2021-12-11 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_remove_places_json_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['order'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
