# Generated by Django 3.2.9 on 2021-12-12 14:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_images_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Полное описание'),
        ),
    ]
